# spring.datasource.url=jdbc:postgresql://localhost:5432/fraedrasil_db
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=fraedrasil_user
spring.datasource.password=02341104

server.port=${PORT:8080}


spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

